# Generated by Django 5.2.3 on 2025-08-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_orderitem_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pièce', 'Pièce'), ('kg', 'Kilogramme'), ('g', 'Gramme'), ('l', 'Litre'), ('cl', 'Centilitre'), ('boîte', 'Boîte'), ('botte', 'Botte'), ('tête', 'Tête'), ('gobelet', 'Gobelet'), ('bouteille 75 cl', 'Bouteille 75 cl'), ('bouteille 50 cl', 'Bouteille 50 cl'), ('bouteille 25 cl', 'Bouteille 25 cl')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productimpact',
            name='unit',
            field=models.CharField(choices=[('pièce', 'Pièce'), ('kg', 'Kilogramme'), ('g', 'Gramme'), ('l', 'Litre'), ('cl', 'Centilitre'), ('boîte', 'Boîte'), ('botte', 'Botte'), ('tête', 'Tête'), ('gobelet', 'Gobelet'), ('bouteille 75 cl', 'Bouteille 75 cl'), ('bouteille 50 cl', 'Bouteille 50 cl'), ('bouteille 25 cl', 'Bouteille 25 cl')], max_length=20),
        ),
    ]
