# Generated by Django 5.2.3 on 2025-08-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_unit_alter_productimpact_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
