# Generated by Django 5.2.3 on 2025-08-11 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('min_orders', models.PositiveIntegerField(default=0)),
                ('min_waste_kg', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('min_co2_kg', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('min_producers_supported', models.PositiveIntegerField(default=0)),
                ('min_savings_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRewardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_waste_kg', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_co2_kg', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_savings_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('producers_supported', models.PositiveIntegerField(default=0)),
                ('seen_producer_ids', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rewards_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ecologicalimpact',
            name='user',
        ),
        migrations.DeleteModel(
            name='ImpactStat',
        ),
        migrations.DeleteModel(
            name='EcologicalImpact',
        ),
    ]
