# Generated by Django 5.2.3 on 2025-08-11 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rewardtier_userrewardprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='benefit_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reward',
            name='benefit_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('blocked', 'Blocked'), ('fulfilled', 'Fulfilled')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='reward',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rewardtier'),
        ),
        migrations.AddField(
            model_name='rewardtier',
            name='benefit_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rewardtier',
            name='benefit_kind',
            field=models.CharField(choices=[('none', 'None'), ('coupon', 'Coupon'), ('freeship', 'Free Shipping')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='reward',
            name='earned_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='reward',
            unique_together={('user', 'tier')},
        ),
    ]
