# Generated by Django 5.2.3 on 2025-08-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reward_benefit_payload_reward_benefit_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productbundle',
            name='sold_bundles',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
