# Generated by Django 5.2.3 on 2025-08-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cart_deactivated_at_cartitem_deactivated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('cart', 'bundle'), name='uniq_active_cartitem'),
        ),
    ]
