# Generated by Django 5.2.3 on 2025-08-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='avoided_co2_kg',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='avoided_waste_kg',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
    ]
