# Generated by Django 5.2.3 on 2025-08-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cartitem_avoided_co2_kg_cartitem_avoided_waste_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='bundle_image',
            field=models.ImageField(blank=True, null=True, upload_to='cart_items/'),
        ),
    ]
