# Generated by Django 5.2.3 on 2025-08-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cartitem_bundle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='company_id_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='company_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='dluo_snapshot',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
