# Generated by Django 5.2.3 on 2025-08-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cartitem_company_id_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='uniq_active_cartitem',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('cart', 'bundle'), name='uniq_active_cart_bundle'),
        ),
    ]
