# Generated by Django 5.2.3 on 2025-08-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_cartitem_uniq_active_cartitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='bundle_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
