# Generated by Django 5.2.3 on 2025-08-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_company_avg_rating_company_ratings_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dossier',
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
