# Generated by Django 5.2.3 on 2025-08-17 00:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_customuser_dossier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='published_date',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(default=1, max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(default=1, max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.blogcategory'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='read_time_min',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
